### ISSUE TITLE
some issues with Ionic app / general

### ISSUE THREAD

**Issue by nicon-dev** [MicrosoftDX/Vorlonjs#173]
I was pretty excited to try Vorlon.js to help me debug real devices.
But when I run it I get some errors without doing a lot.

First:
After install, when I run "vorlon" to start the server I get:

```
$ vorlon
express-session deprecated req.secret; provide secret option ../../../../../../../../.node/lib/node_modules/vorlon/Server/Scripts/vorlon.webServer.js:48:26
```

Then I added
```
<script src="http://localhost:1337/vorlon.js"></script>
```
to the very top of my index.html file, before any other js file get loaded. Is that correct?

Then I run the Ionic webserver with
```
ionic serve
```
Then I get some modernizr warnings, but I think that OK.
But there is also one more error in the dev console:
```
Uncaught TypeError: Cannot read property '__vorlon' of null
````

Althought the Vorlon Dashboard appears and it seems to work, I`m not happy with these erorrs.
Any suggenstions to fix this?

I use:
- Node v0.12.7
- Ionic CLI v1.6.1
- Vorlon v0.0.15

**Comment by meulta** [comment]
Hello,

thanks for trying out Vorlon and giving us your feedbacks so we can make it better ! :)

- The deprecated error is temporary, we are working on the authentication part, should be fixed in 0.0.16. It is already fixed in the latest version on the development-0.0.16 branch
- The TypeError should not happen. What are you calling the Dev Console here? Where do you see this error exaclty, on the dashboard?

Thanks

**Comment by nicon-dev** [comment]
Hi!
thanks for the fast response!
I see this error with the Chrome Dev Tools (Chrome Version 44.0.2403.89 (64-bit))

![image](https://cloud.githubusercontent.com/assets/1035435/8895731/637e65f0-33e4-11e5-9d2f-1f26d41d6d90.png)

System: OSX Yosemite 10.10.4

**Comment by meulta** [comment]
Wow, okay :)

And you still get data on the dashboard coming from the client?
