### ISSUE TITLE
Cannot horizontally scroll in the Network Monitor plugin

### ISSUE THREAD

**Issue by meulta** [MicrosoftDX/Vorlonjs#230]
@cubitouch can you have a look?

**Comment by cubitouch** [comment]
Sorry, got too much notifications, didn't see that before!
I'll sure have a look when I'll have some time.

**Comment by cubitouch** [comment]
After analysis, the plugin "is" scrollable.
![image](https://cloud.githubusercontent.com/assets/7486151/11143925/3e4a5be8-89f9-11e5-922b-4baff84ccb15.png)

But the top bar broke at some point and the horizontal scrollbar is not available anymore.
![image](https://cloud.githubusercontent.com/assets/7486151/11143943/5314eebc-89f9-11e5-954c-2e7557df698b.png)

Is that your issue ?

It seems we have the same issue with all plugins. 
![image](https://cloud.githubusercontent.com/assets/7486151/11143967/7b64de2c-89f9-11e5-9741-c926ea2eeb35.png)

The scrollbar is hidden because of this css on the header tab bar: `.plugin {
  height: calc(100% - 30px);
}`
Updating to `height: calc(100% - 60px);` solve the issue. I have no full-CSS solution to solve this problem right now... Will think about it (if this was the issue you are talking about).

**Comment by deltakosh** [comment]
can you PR the fix?

**Comment by cubitouch** [comment]
I'm still not sure how to properly fix this. It depends on the activated plugins and their position in the tab bars.

A javascript patch seems a little too much for this. I'll ask our integrator if he has an idea without redefining the whole dashboard :)
