### ISSUE TITLE
No such file or directory when running

### ISSUE THREAD

**Issue by NetanelBasal** [MicrosoftDX/Vorlonjs#26]
I install the package like this: ```npm install vorlon -g``` and when i try to run vorlon i get this:
env: node\r: No such file or directory
When i am checking if vorlon is installed by ```which vorlon``` command i get this:
/Users/netanelbasal/.nvm/v0.10.35/bin/vorlon
so its seems to be install, what is the problem?

**Comment by matthiasg** [comment]
same here... 

the `bin/vorlon` file was published with windows line endings instead of unix line endings. Its best to only use unix line endings when publishing to npm or at the very least tell git to checkout the 'binary' files with unix encoding and not use platform encodings.

changing the `/usr/local/lib/node_modules/vorlon/bin/vorlon` to unix endings fixes it

**Comment by NetanelBasal** [comment]
Where i am changing this?

**Comment by deltakosh** [comment]
Should be good now. I changed bin/vorlon endings to UNIX:)
