### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by naresh217** [MicrosoftDX/Vorlonjs#316]
I would like to use my system name instead of localhost for debugging using vorlon. 

Application is running in IPAD and would like to debug from another machine, So i would like to use system name while initiating vorlon in my application

 <script src="https://systemname:1337/vorlon.js"></script>

But it gives "Your connection is private error."

Please can you provide the SSL certificate without hostname or can we edit host name in certificate ?
Attached Screen shot. 

![image](https://cloud.githubusercontent.com/assets/5828286/12889243/071ff000-ce4c-11e5-8d30-28c7f645ddc4.png)

**Comment by cbotsikas** [comment]
@naresh217 you can create your own self-signed certificate and modify config.json to use that instead of the default.
You've mentioned on your previous issue #314, that your application is using SSL. If this application is also hosted on amuslt18634 then you already have a valid certificate and you could use the same for VorlonJS but the procedure depends on your current setup.
If not, you can use OpenSSL to generate one for your VorlonJS host. Assuming that you're working on windows, download and install OpenSSL from https://slproweb.com/products/Win32OpenSSL.html (if you don't know what to download, just pick [Win32 OpenSSL v1.0.2f Light](https://slproweb.com/download/Win32OpenSSL_Light-1_0_2f.exe)). Open a command prompt (cmd) and input the following commands to generate a certificate for your hostname at your Desktop:

cd %USERPROFILE%\Desktop
c:\\**OpenSSL-Win32-light**\bin\openssl.exe req -x509 -sha256 -newkey rsa:2048 -keyout **cert.key** -out **cert.crt** -days 356 -nodes -subj "/CN=**amuslt18634**"

Then you'll need to configure SSLkey to point at your **cert.key** and SSLcert to **cert.crt** at your config.json.

Please note that the above command will generate a certificate valid only when used over https://**amuslt18634**[:port] and will not work on localhost. If you need to support both using one certificate, it's possible through SAN configuration. Also note that you need to install **cert.crt** on your iPad, and other devices, as a Trusted Certificate Authority (CA), otherwise you'll still see errors about the certificate.

**Comment by naresh217** [comment]
Thanks for you help. I was able to create my own certificate. I will update once I completed installing certificate on iPad.

**Comment by naresh217** [comment]
Unable to install a certificate on ipad. Certificate Not verified when created using above steps. 
Please let me what else we can do. 
![image](https://cloud.githubusercontent.com/assets/5828286/13682375/7c65ba52-e6cf-11e5-9cf4-9301fd503c23.png)

**Comment by cbotsikas** [comment]
The "Not verified" is normal (until you actually install it). 
I'm just wondering if renaming it to cert.cer would make any difference.
You might also try opening the file on your ipad's browser (safari?) where you might be able to store it on browser's trusted certificates (don't even know if that's possible, i just [read about it](http://stackoverflow.com/a/13347852)).

**Comment by naresh217** [comment]
Thanks renaming to server.cert worked. 
not worked with amuslt18635 and cert.crt  not sure.

**Comment by cbotsikas** [comment]
Thanks for sharing that it worked. 
it's weird that they only popup installation for .cer and not .crt
Anyway, glad i could help you!

**Comment by naresh217** [comment]
But time after installation, I am trying to access 
https://amuslt18634:1337 on safari it says "Cannot Verify Server Identity"

I am running vorlon on system with name amuslt18634

**Comment by cbotsikas** [comment]
Did the "Not verified" status change?
Can you share a screenshot of the "More Details" option you had on your previous image?

**Comment by naresh217** [comment]
Yes Now it is Verified.

Attached Screenshots

**Comment by cbotsikas** [comment]
Is it possible that you can just visit https://amuslt18634:1337 from safari and on the popup error click Details->Accept?
The other thing i'm thinking is that, you may need to actually have two certificates for iOS. One CA and one for the Vorlonjs. (the solution i gave you above gives you a valid self signed certificate but there is no CA and maybe iOS/Safari doesn't like that). In that case you need to create a CA and install that the way you did earlier) and also generate a second certificate to use with the vorlon. Check [here, tip #5](https://blog.httpwatch.com/2013/12/12/five-tips-for-using-self-signed-ssl-certificates-with-ios/). You will need to install "myCA.cer" on your iPad (/CN="My Custom CA", can be any text you like)  and for vorlon you need the "mycert1.cer" (/CN=www2.mysite.com, in your case is /CN=amuslt18634)

**Comment by cbotsikas** [comment]
and just to make sure, does the certificate and address https://amuslt18634:1337 work on your PC with Chrome?

**Comment by naresh217** [comment]
Yes its works on my machine with https://amuslt18634:1337.

**Comment by naresh217** [comment]
in the pop up i only have "OK" to click. 

I created another myCA.cer and installed on Ipad but error still exists. 

Do i need to do any thing in config.json, i just modified paths to,useSSL to true,  SSLKey and SSLcert to load my amuslt18634 certificates, do i need to update to pick myCA.cer ?

**Comment by naresh217** [comment]
Do you have any other pointers to try ?
